import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';
import { BeautyAttributes } from './analysis/beauty-analysis.contract';

export type BeautyGuideStatus = 'processing' | 'ready' | 'unsuitable' | 'failed';
export type BeautyGuideFailureCode =
  | 'timeout'
  | 'provider_error'
  | 'provider_busy'
  | 'provider_unreachable'
  | 'invalid_output'
  | 'unconfigured'
  | 'unsuitable';

/**
 * A customer's private Beauty Guide. Everything AI-derived here is ADVISORY: no booking,
 * pricing, availability or payment code reads any of these columns. The duration
 * estimates are informational copy only -- slot generation keeps using
 * salon_services.duration_min.
 *
 * `rawAnalysis` keeps the validated contract payload together with provider / model /
 * prompt / schema versions, so an existing guide stays reproducible and is never silently
 * regenerated by a newer model. `providerCalled` is what usage limits count: a guide
 * served from the per-user duplicate cache, or rejected before reaching the provider,
 * never consumes quota.
 */
@Entity('beauty_guides')
export class BeautyGuide {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id' })
  userId: string;

  @Column({ type: 'varchar', length: 20, default: 'processing' })
  status: BeautyGuideStatus;

  // Private-store key (never a URL). Served only through authenticated endpoints.
  @Column({ name: 'image_key', type: 'varchar', length: 200 })
  imageKey: string;

  @Column({ name: 'image_sha256', type: 'char', length: 64 })
  imageSha256: string;

  @Column({ name: 'source_portfolio_item_id', type: 'uuid', nullable: true })
  sourcePortfolioItemId: string | null;

  @Column({ type: 'varchar', length: 20, nullable: true })
  domain: string | null;

  @Column({ name: 'look_summary_fa', type: 'text', nullable: true })
  lookSummaryFa: string | null;

  @Column({ name: 'stylist_request_fa', type: 'text', nullable: true })
  stylistRequestFa: string | null;

  @Column({ name: 'duration_min_estimate', type: 'int', nullable: true })
  durationMinEstimate: number | null;

  @Column({ name: 'duration_max_estimate', type: 'int', nullable: true })
  durationMaxEstimate: number | null;

  // AI-detected, then overwritten key-by-key by the customer's own corrections.
  @Column({ type: 'jsonb', default: () => "'{}'" })
  attributes: BeautyAttributes;

  @Column({ name: 'discussion_points', type: 'jsonb', default: () => "'[]'" })
  discussionPoints: string[];

  @Column({ name: 'maintenance_ai', type: 'jsonb', default: () => "'[]'" })
  maintenanceAi: string[];

  @Column({ name: 'safety_note', type: 'varchar', length: 30, nullable: true })
  safetyNote: string | null;

  @Column({ name: 'raw_analysis', type: 'jsonb', nullable: true })
  rawAnalysis: unknown;

  @Column({ type: 'varchar', length: 40, nullable: true })
  provider: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true })
  model: string | null;

  @Column({ name: 'prompt_version', type: 'varchar', length: 20, nullable: true })
  promptVersion: string | null;

  @Column({ name: 'schema_version', type: 'varchar', length: 20, nullable: true })
  schemaVersion: string | null;

  @Column({ name: 'provider_called', default: false })
  providerCalled: boolean;

  @Column({ name: 'failure_code', type: 'varchar', length: 30, nullable: true })
  failureCode: BeautyGuideFailureCode | null;

  @Column({ name: 'analyzed_at', type: 'timestamptz', nullable: true })
  analyzedAt: Date | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}
